
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";

import "./styles/globals.scss";
const inter = Montserrat({ subsets: ["latin"], weight: ["100", "300", "500", "700"] });



export const metadata: Metadata = {
  title: "MKS",
  description: "Generated by create next app",
  icons: "/mks.jpg",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
          {children}
      </body>
    </html>
  );
}
